language: c++

services:
  - docker

before_install:
  - docker pull xyzsam/smaug:latest
  - docker run -it --rm --mount source=smaug-workspace,target=/workspace xyzsam/smaug:latest

script:
  - |
    cd /workspace/smaug
    make all -j2
    make test-run -j2

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - slxi1202@gmail.com
      - yaoyuannnn@gmail.com
