# Performance tests for this library.

include common/Makefile.arch

TEST_TARGET = test_$(TEST)
all: $(TEST_TARGET)

test_eigen_%:
	@make -f common/Makefile.perftests.eigen --no-print-directory $@

test_mkl_%:
	@make -f common/Makefile.perftests.mkl --no-print-directory $@

clean-perftests:
	@make -f common/Makefile.perftests.eigen --no-print-directory clean
	@make -f common/Makefile.perftests.mkl --no-print-directory clean
